language: node_js
node_js:
    - "10.16.0"

build:
    install:
        - npm install
    linting:
        - npm run lint
    deploy:
        - if [ "$TRAVIS_BRANCH" = "master" ]; then npm run deploy fi
