language: node_js
node_js:
    - "10.16.0"

build:
    install: npm ci
    script: echo "npm test temporarily disabled"
    linting: npm run lint
    deploy: if [ "$TRAVIS_BRANCH" = "master" ]; then npm run deploy fi
